# Site
name: 'Sandro Felder'
description: 'Another blog where nobody cares'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
host: '0.0.0.0'
baseurl: ''
#disqus: 'sandrojekyll'
email: 'sandrek@gmail.com'
# mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    sandro:
      name:           Sandro
      site:           https://sandrofelder.ch
      avatar:         assets/images/me_avatar.png
      bio:            "I am just a guy that cares."
      email:          sandro.felder@gmail.com
      twitter:        https://www.linkedin.com/in/sandrofelder/
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sandro
      avatar: /assets/images/me_avatar.png
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]